<?php
/**
 * Alert users about the use of cookies.
 *
 * @wordpress-plugin
 * Plugin Name: Cookie Consent (MU)
 * Description: The most popular solution to the EU cookie law.
 * Version: 0.1.2
 * Plugin URI: https://cookieconsent.insites.com/download/
*/

add_action( 'wp_footer', function () {

    // EDIT here!
    $policy_url = '/cookie-policy/';

    $cookieconsent_template = '
<!-- Cookie Consent by Insites -->
<style scoped>@import url("//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css");</style>
<script async src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"
 integrity="sha384-PDjg2ZdS3khPzd53i18+7tzB32JVQfFMrTXYo21RqPgUmEVAPwIhxOUF/8sP79CS" crossorigin="anonymous"></script>
<script>

    // EDIT here!
    // JavaScript generated by https://cookieconsent.insites.com/download/
    // if (typeof window.cookieconsent !== "object") { return; }
    // "href": "%s"

</script>';

    printf( $cookieconsent_template, $policy_url );
}, 51 );
